apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: frontend
spec: 
  containers:
  - name: first-container
    image: nginx 
    ports: 
    - containerPort: 80
    restartPolicy: Always